### ISSUE TITLE
Random spikes in power consumption [kWh] for all Z-Wave modules

### ISSUE THREAD

**Issue by Alfamonk** [hassio-addons/addon-zwave-js-ui#438]
Hello,

Since I have moved all my Z-Wave devices from Fibaro Home Center 2 to Home Assistant (using Aeotec Z-Stick Gen5) i see random spikes in power consumption, which makes the Energy panel and every consumption statistic unusable. I have tried to understand if the spikes happen at a specific time, or maybe just some specific devices have the issue (in hope those devices are broken and need to be replaced). But no. This happen to almost all my Z-Wave plugs and dimmers, at completely random times.

What happens exactly? Well, let's take for example "sensor.birou_plug_internet_electric_consumption_kwh" (It's a Fibaro Wall Plug). It's usually under 1kWh per day. But today 8:35 AM, there is a recording for 3546.82 kWh, which is impossible!

Another example is one with negative values, which should also be impossible for a cumulative attribute, like kWh (unless you reset it to 0). In this case, it's "sensor.smart_meter_electric_consumed_kwh" from a Qubino Smart Meter - ZMNHTD1. The last value in consumption was above 34,531.5 kWh. But today at 8:36 AM, there is a recording for only 517.2 kWh, which messes all the statistics in Energy.

There must be something related to Z-Wave JS, as my other modules that use Zigbee don't have this issue.

What have i tried? Well, I have healed the network, I have updated Aeotec Z-Stick Gen5 to the latest firmware, I have updated Home Assistant and all addons to the latest versions. Restarted Home Assistant, restarted VMWare, changed the stick location (using an USB extender to not interfere with other devices)... I don't know what else to do.

The only fix I found was to write down the entity with issues, go into Developer Tools - Statistics, search for the entity, go at that exact time where the spike happened, and replace it with 0 values. It was OK for a while (when I had like 3-4 items), but now that I moved completely to Home Assistant, it's a real pain! 20-30 devices per day going to random values... it's just killing me.

Can you please let me know what can I do to fix this?
Thank you in advance!

P.S. I must admit I have also posted this on github.com/home-assistant/core, but as I haven't received any answers, I hoped I will get some solution in here. Thanks!

**Comment by TheDK** [comment]
This issue will be closed pretty fast as this add-on only wraps Z-Wave JS UI and anything with regard to the behaviour of the driver would need to be placed upstream. Also, HA Core can't do anything about it, because as far as I analyzed this issue myself either the Fibaro modules are reporting wrong values or Z-Wave JS is interpreting the message wrong from time to time, so the Z-Wave layer would be the right point to address, here:
https://github.com/zwave-js/node-zwave-js/issues

This thread hear covers an issue with updates not coming through - different thing, but gives some insight into how Z-Wave works:
https://github.com/zwave-js/node-zwave-js/issues/5094

I do have the same issues and work around them by using a) filtering on critical sensor entities to ignore outliers and b) some automation logic to combine all energy readings e.g. for lighting to work around this.
