### ISSUE TITLE
All `update.<name>_firmware` Entities Unavailable after V1.13

### ISSUE THREAD

**Issue by PablaV** [hassio-addons/addon-zwave-js-ui#517]
# Problem/Motivation

All the `update.<name>_firmware` entities have become unavailable after the recent 1.13 update. It's state that the integration is no longer being provided. Not sure if this is being deprecated, but before I delete these entities want to make sure its expected.

## Expected behavior

> (What you expected to happen)

The update entities usually are available

> (What actually happened)

No steps needed the entities stay unavailable regardless of states

**Comment by frenck** [comment]
Hi there @PablaV 👋 

This is not something the add-on itself can do anything about. Add-on wrap existing software (in this case Z-Wave JS UI) and make them easily installable/integrated with Home Assistant.

The functionality inside the software wrapped is not created in this add-on repository. Please report your issue upstream with Z-Wave JS. Once the issue is addressed and release, the add-on will receive an update.

../Frenck

**Comment by PablaV** [comment]
Will do thanks!
