### ISSUE TITLE
WebUI isn't working anymore in 2.1.1 -> 502 Bad Gateway error

### ISSUE THREAD

**Issue by ceesvanegmond** [hassio-addons/addon-zwave-js-ui#594]
# Problem/Motivation

Since latest update (to 2.1.1) the addon is starting; but cannot get to the web ui.

## Expected behavior

The web ui (just as before)

## Actual behavior

I'm getting an 502 Bad Gateway error; only on this specific addon. Other addons are working.

## Steps to reproduce

Update to latest version and try to open the webui from the home assistant menu on the left.
I also don't see nothing particular in the error logs. I can still interact with the API so that's good; but it seems that the UI itself is broken. 

<img width="1512" alt="Screenshot 2023-10-12 at 20 49 03" src="https://github.com/hassio-addons/addon-zwave-js-ui/assets/883497/5772503a-7984-434f-915c-be6440b192c7">

**Comment by tjmjansen** [comment]
Experiencing the same

**Comment by steve-sellers** [comment]
Same here after the HA update. The 502 errors don't seem deterministic in network logs... as a result, sometimes it will pop up the dialog "The add-on seems to not be ready, it might still be starting. Do you want to try again?", sometimes it will load an HTML page stating 502, other times it will partially load the page but be missing random elements and in nearly all attempts is unusable. I got lucky once to have my devices load, no such luck since.

**Comment by tjmjansen** [comment]
Seems more related to 2023.10.2 of HA core, i had to downgrade to .1 to resolve this, only rolling back to 2.1.0 did not help. Now it al works again on 10.1

**Comment by ceesvanegmond** [comment]
Can confirm it works again in Home Assistant 2023.10.3
