### ISSUE TITLE
'ZMNHXD by Qubino' Smartmeter stops updating after upgrade to 3.8.1

### ISSUE THREAD

**Issue by Edwintenhaaf** [hassio-addons/addon-zwave-js-ui#678]
# Problem/Motivation

'ZMNHXD by Qubino' Smartmeter stops updating after upgrade to 3.8.1
Firmware: 50.6

## Expected behavior

Update device entities every x seconds

## Actual behavior

Sensor update stops after upgrade within few minutes

## Steps to reproduce

Upgrade to 3.8.1 updating sensors stops within few minutes
Restore to 3.8.0 updating sensors runs as expected

## Proposed changes
?

**Comment by GvnCampbell** [comment]
I have a number of devices doing the same thing and randomly going unavailable.

Is see that there was a bug introduced in node-zwave-js 12.11.1 that may be related and it looks like it was fixed in 12.11.2 but looks like the dependencies for addon-zwave-js-ui need to be bumped up first before we see it.  

https://github.com/zwave-js/node-zwave-js/releases/tag/v12.11.2
